AppTitle: Employee demo
AppIcon: FireBirdSql_120


Databases:
  Main: DBX
    Connection:
      DriverName: Firebird
      DataBase: localhost:EMPLOYEE
      User_Name: SYSDBA
      Password: masterkey
      #ServerCharSet: UTF8
      WaitOnLocks: True
      IsolationLevel: ReadCommitted
      Trim Char: False

Auth: TextFile
  IsClearPassword: True
  Defaults:
    UserName: guest
    .Password: password

AccessControl: Null

Login:
  Controller:
    BorderPanel:
      NorthView:
        Controller: HtmlPanel
          Height: 120
          Html: |
            <div style="text-align: center">
              <p/>
              <p><img src="%IMAGE(Firebird_Employee)%"></img></p>
              <p><H1>Firebird Employee Demo</H1></p>
              <p/>
            </div>
    ExtraWidth: 400
    LabelWidth: 150
    ExtraHeight: 150
    LocalStorage:
      Mode: Password
      AskUser: True
        .Default: False

# Change this to use a custom view for the home page.
# Alternatively, customize the Home view by replacing its controller.
# Default: Home.
#HomeView: Home

Ext:
  Theme: access
# Either utf-8 or a SBCS corresponding to the system code page
# (such as iso-8859-1 for Western Europe). Defaults to utf-8.
Charset: utf-8

FastCGI:
  TCPPort: 2203
LanguageId: en
