AppTitle: Tasks & Activities

Databases:
  Main: DBX
    Connection:
      DriverName: Firebird
      DataBase: localhost:TASKITTO
      User_Name: SYSDBA
      Password: masterkey
      ServerCharSet: UTF8
      WaitOnLocks: True
      IsolationLevel: ReadCommitted
      Trim Char: False

Auth: DB
  IsClearPassword: True
  Defaults:
    UserName: admin
#Password: password

AccessControl: Null

# Change this to use a custom view for the home page.
# Alternatively, customize the Home view by replacing its controller.
# Default: Home.
HomeView: HomeMini

Ext:
  Theme: gray
  URL: /ext

LanguageId: en
# Either utf-8 or a SBCS corresponding to the system code page
# (such as iso-8859-1 for Western Europe). Defaults to utf-8.
Charset: utf-8

FastCGI:
  TCPPort: 2202
